Algoritmo "para ex1"
// Disciplina   : [Algoritmos]
// Professor   : Francisco Vichi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/05/2022
Var
// Seção de Declarações das variáveis 
   c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para c <- 1 ate 20 passo 1 faca
        escreval(c, "- ", "Eu gosto de estudar algoritmos!")
   fimpara

Fimalgoritmo